baseURL = "http://makenowjust-labo.github.io/redos/"
languageCode = "en-us"
title = "redos | MakeNowJust-Labo"
copyright = "2020 (C) TSUYUSATO \"MakeNowJust\" Kitsune"

[params]
name = "redos"
description = "A vulnerable RegExp (ReDoS) checker."
github = "MakeNowJust-Labo/redos"
