name: Maven Release

on:
  push:
    branches: [master]
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish to Maven Central
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-gpg@v2
      - name: Publish
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
