name: NPM Release

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.14

      - name: Build
        run: |
          sbt recheckJS/fullOptJS
          cp modules/recheck/js/target/scala-2.13/recheck-opt.js* packages/recheck/

      - uses: JS-DevTools/npm-publish@v1
        with:
          package: packages/recheck/package.json
          token: ${{ secrets.NPM_TOKEN }}
