name: NPM Release

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.14

      - name: Build
        run: |
          sbt js/fullLinkJS
          cp modules/recheck-js/target/scala-2.13/recheck-js-opt/* packages/recheck/
          cd packages/recheck
          npx esbuild recheck.js --bundle --platform=node --outfile=recheck.bundle.js

      - uses: JS-DevTools/npm-publish@v1
        with:
          package: packages/recheck/package.json
          token: ${{ secrets.NPM_TOKEN }}
